---
# tasks file for install_docker
- name: "Generate install docker sh"
  command:
    cmd: "curl -fsSL https://get.docker.com -o get-docker.sh"

- name: "Execute install docker"
  command:
    cmd: "sh get-docker.sh"
    
- name: "Add Docker Privilege"
  command:
    cmd: "sudo usermod -aG docker ubuntu"
    
- name: "start docker"
  service:
    name: docker
    state: started
    enabled: yes
